services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - tab-generator
  tab-generator:
    build: ./tab-generator
    ports:
      - "8081:8080"
    depends_on:
      - audio-analyzer
  
  audio-analyzer:
    build: ./audio-analyzer
    env_file:
      - /audio-analyzer/.env
    ports:
      - "50051:50051"